# Generated by Django 3.2.4 on 2021-06-18 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=10, unique=True, verbose_name='Зачетная книжка')),
                ('last_name', models.CharField(max_length=30, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=30, verbose_name='Имя')),
                ('second_name', models.CharField(blank=True, default='', max_length=30, verbose_name='Отчество')),
                ('basis', models.CharField(choices=[('Б', 'Бюджет'), ('К', 'Контракт'), ('ИГ', 'ИнГосЛиния')], default='Б', max_length=20, verbose_name='Основа обучения')),
                ('citizenship', models.CharField(choices=[('РФ', 'Россия'), ('Ин', 'Иностранец')], default='РФ', max_length=20, verbose_name='Гражданство')),
                ('level', models.CharField(choices=[('Бак', 'Бакалавриат'), ('Маг', 'Магистратура')], max_length=20, verbose_name='Уровень обучения')),
                ('group', models.CharField(choices=[('ТТ', 'ТТ'), ('ЭЭ', 'ЭЭ'), ('ИС', 'ИС'), ('ЗК', 'ЗК'), ('ТТм', 'ТТм'), ('ЗКм', 'ЗКм'), ('ЭЭм', 'ЭЭм'), ('ТГВм', 'ТГВм'), ('ВВм', 'ВВм')], max_length=10, verbose_name='Группа')),
                ('start_date', models.DateField(verbose_name='Дата зачисления')),
                ('status', models.CharField(choices=[('ЯС', 'Является студентом'), ('АО', 'Академический отпуск'), ('ОТ', 'Отчислен'), ('Вк', 'Выпускник')], default='ЯС', max_length=30, verbose_name='Текущий статус')),
                ('comment', models.CharField(blank=True, default='', max_length=255, verbose_name='Примечание')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Запись создана')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Запись обновлена')),
            ],
            options={
                'verbose_name': 'Обучающийся',
                'verbose_name_plural': 'Обучающиеся',
                'ordering': ['last_name', 'first_name', 'second_name', 'status'],
            },
        ),
    ]
