# Generated by Django 3.2.4 on 2021-06-04 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=10, verbose_name='Зачетная книжка')),
                ('last_name', models.CharField(max_length=30, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=30, verbose_name='Имя')),
                ('second_name', models.CharField(blank=True, max_length=30, verbose_name='Отчество')),
                ('basis', models.CharField(choices=[('К', 'Контракт'), ('Б', 'Бюджет'), ('ИГ', 'ИнГосЛиния')], max_length=20, verbose_name='Основа обучения')),
                ('citizenship', models.CharField(choices=[('РФ', 'Россия'), ('Ин', 'Иностранец')], max_length=20, verbose_name='Гражданство')),
                ('level', models.CharField(choices=[('Бак', 'Бакалавриат'), ('Маг', 'Магистратура')], max_length=20, verbose_name='Уровень обучения')),
                ('start_date', models.DateField(verbose_name='Дата зачисления')),
                ('status', models.CharField(choices=[('ЯС', 'Является студентом'), ('АО', 'Академический отпуск'), ('ОТ', 'Отчислен')], max_length=30, verbose_name='Текущий статус')),
                ('comment', models.CharField(blank=True, max_length=255, verbose_name='Примечание')),
            ],
        ),
    ]
