# Generated by Django 3.2.4 on 2021-06-21 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.IntegerField(unique=True, verbose_name='Зачетная книжка'),
        ),
    ]
