# Generated by Django 3.2.4 on 2021-06-04 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='group',
            field=models.CharField(choices=[('ТТ', 'ТТ'), ('ЭЭ', 'ЭЭ'), ('ИС', 'ИС'), ('ЗК', 'ЗК'), ('ТТм', 'ТТм'), ('ЗКм', 'ЗКм'), ('ЭЭм', 'ЭЭм'), ('ТГВм', 'ТГВм'), ('ВВм', 'ВВм')], default='default', max_length=10, verbose_name='Группа'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.CharField(max_length=10, unique=True, verbose_name='Зачетная книжка'),
        ),
    ]
