# Generated by Django 3.2.4 on 2021-07-04 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subject', '0001_initial'),
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='subjects',
            field=models.ManyToManyField(through='subject.GroupSubject', to='subject.Subject'),
        ),
    ]
