# Generated by Django 3.2.4 on 2021-06-09 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_auto_20210604_2145'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['last_name']},
        ),
        migrations.AlterField(
            model_name='student',
            name='basis',
            field=models.CharField(choices=[('Б', 'Бюджет'), ('К', 'Контракт'), ('ИГ', 'ИнГосЛиния')], default='Б', max_length=20, verbose_name='Основа обучения'),
        ),
        migrations.AlterField(
            model_name='student',
            name='citizenship',
            field=models.CharField(choices=[('РФ', 'Россия'), ('Ин', 'Иностранец')], default='РФ', max_length=20, verbose_name='Гражданство'),
        ),
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('ЯС', 'Является студентом'), ('АО', 'Академический отпуск'), ('ОТ', 'Отчислен')], default='ЯС', max_length=30, verbose_name='Текущий статус'),
        ),
    ]
