# Generated by Django 3.2.4 on 2021-06-09 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_auto_20210609_1205'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['last_name'], 'verbose_name_plural': 'Обучающиеся'},
        ),
        migrations.AlterField(
            model_name='student',
            name='comment',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Примечание'),
        ),
        migrations.AlterField(
            model_name='student',
            name='second_name',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='Отчество'),
        ),
    ]
