# Generated by Django 3.2.4 on 2021-06-22 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_auto_20210622_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='group',
            field=models.CharField(choices=[('ТТ', 'ТТ'), ('ЭЭ', 'ЭЭ'), ('ИС', 'ИС'), ('ЗК', 'ЗК'), ('ТТм', 'ТТм'), ('ЗКм', 'ЗКм'), ('ЭЭм', 'ЭЭм'), ('ТГВм', 'ТГВм'), ('ВВм', 'ВВм')], max_length=10, verbose_name='Группа'),
        ),
        migrations.DeleteModel(
            name='Group',
        ),
    ]
