# Generated by Django 3.2.4 on 2021-06-18 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=150, verbose_name='Наименование дисциплины')),
                ('cathedra', models.CharField(choices=[('ФИЭиГХ', (('КВиЭ', 'водопользования и экологии'), ('КГЗиК', 'геодезии, землеустройства и кадастров'), ('КСФиХ', 'строительной физики и химии'), ('КТГВ', 'теплогазоснабжения и вентиляции'), ('КЭиЭ', 'электроэнергетики и электротехники'))), ('СФ', (('КАДМиТ', 'автомобильных дорог, мостов и тоннелей'), ('КАСК', 'архитектурно-строительных конструкций'), ('КГЕО', 'геотехники'), ('КЖБК', 'железобетонных и каменных конструкций'), ('КИТ ', 'информационных технологий'), ('КМиДК', 'металлических и деревянных конструкций'), ('КМАТ', 'математики'), ('КОС', 'организации строительства'), ('КСМ', 'строительной механики'), ('КТСП', 'технологии строительного производства'), ('КТСМиМ', 'технологии строительных материалов и метрологии')))], max_length=100, verbose_name='Кафедра')),
                ('teacher', models.CharField(blank=True, help_text='Фамилия И.О.', max_length=150, verbose_name='Преподаватель')),
                ('att_date', models.DateField(blank=True, null=True, verbose_name='Дата сдачи')),
                ('comment', models.CharField(blank=True, default='', max_length=255, verbose_name='Примечание')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Запись создана')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Запись обновлена')),
            ],
            options={
                'verbose_name': 'Дисциплина',
                'verbose_name_plural': 'Дисциплины',
                'ordering': ['subject_name', '-att_date'],
            },
        ),
    ]
