# Generated by Django 3.2.4 on 2021-07-04 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(choices=[('1-1', '1-1'), ('1-2', '1-2'), ('2-3', '2-3'), ('2-4', '2-4'), ('3-5', '3-5'), ('3-6', '3-6'), ('4-7', '4-7'), ('4-8', '4-8')], max_length=5, verbose_name='Семестр')),
                ('groups', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.group')),
            ],
            options={
                'verbose_name': 'Семестр',
                'verbose_name_plural': 'Семестры',
                'ordering': ['semester'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=150, verbose_name='Наименование дисциплины')),
                ('cathedra', models.CharField(choices=[('ФИЭиГХ', (('КВиЭ', 'водопользования и экологии'), ('КГЗиК', 'геодезии, землеустройства и кадастров'), ('КСФиХ', 'строительной физики и химии'), ('КТГВ', 'теплогазоснабжения и вентиляции'), ('КЭиЭ', 'электроэнергетики и электротехники'))), ('СФ', (('КАДМиТ', 'автомобильных дорог, мостов и тоннелей'), ('КАСК', 'архитектурно-строительных конструкций'), ('КГЕО', 'геотехники'), ('КЖБК', 'железобетонных и каменных конструкций'), ('КИТ ', 'информационных технологий'), ('КМиДК', 'металлических и деревянных конструкций'), ('КМАТ', 'математики'), ('КОС', 'организации строительства'), ('КСМ', 'строительной механики'), ('КТСП', 'технологии строительного производства'), ('КТСМиМ', 'технологии строительных материалов и метрологии')))], max_length=100, verbose_name='Кафедра')),
                ('teacher', models.CharField(blank=True, help_text='Фамилия И.О.', max_length=150, verbose_name='Преподаватель')),
                ('att_date', models.DateField(blank=True, null=True, verbose_name='Дата сдачи')),
                ('comment', models.CharField(blank=True, default='', max_length=255, verbose_name='Примечание')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Запись создана')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Запись обновлена')),
                ('groups', models.ManyToManyField(through='subject.GroupSubject', to='student.Group')),
            ],
            options={
                'verbose_name': 'Дисциплина',
                'verbose_name_plural': 'Дисциплины',
                'ordering': ['subject_name', '-att_date'],
            },
        ),
        migrations.AddField(
            model_name='groupsubject',
            name='subjects',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subject.subject'),
        ),
    ]
