# Generated by Django 3.2.4 on 2021-07-14 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_auto_20210714_1014'),
        ('subject', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='form_control',
            field=models.CharField(choices=[(1, 'Экзамен'), (2, 'Диффзачет'), (3, 'Зачет'), (4, 'Курсовой проект'), (5, 'Курсовая работа')], default='Экзамен', max_length=20, verbose_name='Форма контроля'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='groupsubject',
            name='semester',
            field=models.IntegerField(choices=[(1, '1-1'), (2, '1-2'), (3, '2-3'), (4, '2-4'), (5, '3-5'), (6, '3-6'), (7, '4-7'), (8, '4-8')], verbose_name='Семестр'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='groups',
            field=models.ManyToManyField(through='subject.GroupSubject', to='student.Group', verbose_name='Группы'),
        ),
    ]
