# Generated by Django 3.2.4 on 2021-07-14 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_result'),
        ('subject', '0002_auto_20210714_1014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupsubject',
            name='groups',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.group', verbose_name='Группа'),
        ),
        migrations.AlterField(
            model_name='groupsubject',
            name='subjects',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subject.subject', verbose_name='Дисциплина'),
        ),
    ]
