# Generated by Django 3.2.4 on 2021-07-14 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0003_auto_20210714_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='form_control',
            field=models.IntegerField(choices=[(1, 'Экзамен'), (2, 'Диффзачет'), (3, 'Зачет'), (4, 'Курсовой проект'), (5, 'Курсовая работа')], verbose_name='Форма контроля'),
        ),
    ]
